apiVersion: v1
kind: Service
metadata:
  name: tomaskulcsarmslearnaksworkshopratingsapi
spec:
  selector:
    app: tomaskulcsarmslearnaksworkshopratingsapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
